name: apply kpm to kernel image
description: apply kpm patch to kernel image from sukisu

runs:
 using: composite
 steps:
   - name: download sukisu repo and run script to apply kpm compatibility
     shell: bash
     run: |
      git clone https://github.com/SukiSU-Ultra/SukiSU_patch.git
      cp SukiSU_patch/kpm/patch_linux "$ANYKERNEL3"
      
      cd "$ANYKERNEL3"
      chmod +x patch_linux
      
      if [[ -f Image.gz ]]; then
          # decompress .gz to raw
          gzip -d Image.gz
          
          # apply kpm patch
          ./patch_linux
          echo "KPM patch applied successfully!"
          rm patch_linux
          rm Image
          mv oImage Image
          
          # compress it back to gz
          gzip -9 Image
      else
          ./patch_linux
          echo "KPM patch applied successfully!"
          rm patch_linux
          rm Image
          mv oImage Image
      fi
